config/routes.rb
Rails.application.routes.draw do
  # match the twitter call back path and point it to some controller action
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('welcome#index')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  # get 'welcome/index'
  root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  def self.from_omniauth(auth_hash)
    #Look up the user or create them using keys in the auth hash
    user = where(provider: auth_hash.provider, uid: auth_hash.uid).first_or_create
    user.update(
      name: auth_hash.info.name,
      profile_image: auth_hash.info.image,
      twitter_user_name: auth_hash.info.nickname,
      token: auth_hash.credentials.token,
      secret: auth_hash.credentials.secret
    )
    user
  end

  # token and secret is what came back from omniauth and this was saved to the user database.
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # to enable the current_user variable to be used in the view file
  helper_method :current_user

end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

  def index
    @followers = Follower.all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # complete omniauth authentication and crate user record in database
    # raise env["omniauth.auth"].to_yaml

    @user = User.from_omniauth(auth_hash)
    session[:user_id] = @user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "You are signed out"
  end

  protected

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  require 'twitter_api'
  
  def index
    @twitter_api = TwitterApi.new(current_user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def parsed_tweet(tweet)
    _parsed_tweet = tweet.text.dup

    tweet.urls.each do |entity|
      html_link = link_to(entity.display_url.to_s, entity.expanded_url.to_s, target: 'blank')
      _parsed_tweet.sub!(entity.url.to_s, html_link)
    end

    tweet.media.each do |entity|
      html_link = link_to(entity.display_url.to_s, entity.expanded_url.to_s, target: 'blank')
      _parsed_tweet.sub!(entity.url.to_s, html_link)
    end

    _parsed_tweet.html_safe
  end
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTwitterApi</title>
    <link href="//fonts.googleapis.com/css?family=Raleway:400,700" rel="stylesheet">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    




    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<div class="wrapper">
  <h1>OMNIAUTH AND TWITTER API</h1>

  <!-- <%= link_to "Sign in with Twitter", "/auth/twitter" %> -->
  <% if current_user %>
    <div id="sign_in_wrapper">
      <p id="sign_in">Signed in as <span><%= current_user.name %></span> </p>
      <%= image_tag current_user.profile_image, class: "profile_image" %>
      <p><%= link_to "Sign out", signout_path, id: "sign_out" %></p>
    </div>

    <div class="public_tweets">
      <p>Latest tweet from <%= current_user.name %>:</p>
      <% cache('our_public_tweets', expires_in: 6.hours) do %>
        <% @twitter_api.our_public_tweets.each do |tweet| %>
          <%= parsed_tweet(tweet) %>
        <% end %>
      <% end %>
    </div>

    <ul class="followers">
      <p>First 20 followers for <%= current_user.name %>:</p>
      <% cache('followers', expires_in: 6.hours) do %>
        <% @twitter_api.followers.each do |follower| %>
          <li><%= follower.name %></li>
          <hr>
        <% end %>
      <% end %>
    </ul>

  <% else %>

    <%= link_to "/auth/twitter", id: "link_button" do %>
      <i class="fa fa-twitter fa-3x"></i>
    <% end %>
    <p class="date">Click the twitter icon to sign in and view followers</p>

  <% end %>
</div>